spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            provider: wso2
            authorization-grant-type: authorization_code
            client-id: MFrlQ_RW57B77xwGjpUnGkicQs4a
            client-secret: N8jJ7pHluH35wsEdlKBImx13Wuka
            redirect-uri: "{baseUrl}/login/oauth2/code/wso2"
            scope: openid,profile
        provider:
          wso2:
            issuer-uri: ${WSO2IS_URL:https://localhost:9443}/oaut