/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.angadi.springoauthclient.business.services.Requests;

import java.util.Collection;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.annotation.Generated;
import jakarta.annotation.Nonnull;
import lombok.ToString;

/**
 * DocumentsRequest
 */
@JsonPropertyOrder({
  DocumentsServiceRequest.JSON_PROPERTY_DOC_NAME
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-25T23:15:31.966220200-04:00[America/New_York]", comments = "Generator version: 7.15.0")
@ToString
public class DocumentsServiceRequest {
  public static final String JSON_PROPERTY_DOC_NAME = "docName";
  private Collection<String> docName;

  public DocumentsServiceRequest() {
  }

  public DocumentsServiceRequest docName(Collection<String> docName) {
    
    this.docName = docName;
    return this;
  }

  /**
   * Get docName
   * @return docName
   */
  @Nonnull
  @JsonProperty(JSON_PROPERTY_DOC_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Collection<String> getDocName() {
    return docName;
  }


  @JsonProperty(JSON_PROPERTY_DOC_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocName(@Nonnull Collection<String> docName) {
    this.docName = docName;
  }


  @Override
  public int hashCode() {
    // A common and effective way is to use Objects.hash()
    int hashCode = 17;
    if(docName!=null)
    for (String e : docName) {
      hashCode = 31 * hashCode + (e == null ? 0 : e.hashCode());
    }
    return hashCode;
  }


}

