/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.angadi.springoauthclient.business.services.Responses;

import java.time.LocalDate;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.annotation.Generated;
import jakarta.annotation.Nullable;

/**
 * Document
 */
@JsonPropertyOrder({
  DocumentsServiceResponse.JSON_PROPERTY_DOC_NAME,
  DocumentsServiceResponse.JSON_PROPERTY_DOC_LOCATION,
  DocumentsServiceResponse.JSON_PROPERTY_DOC_TYPE,
  DocumentsServiceResponse.JSON_PROPERTY_DOC_YEAR
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-25T23:15:31.966220200-04:00[America/New_York]", comments = "Generator version: 7.15.0")
public class DocumentsServiceResponse {
  public static final String JSON_PROPERTY_DOC_NAME = "docName";
  @Nullable
  private String docName;

  public static final String JSON_PROPERTY_DOC_LOCATION = "docLocation";
  @Nullable
  private String docLocation;

  public static final String JSON_PROPERTY_DOC_TYPE = "docType";
  @Nullable
  private String docType;

  public static final String JSON_PROPERTY_DOC_YEAR = "docYear";
  @Nullable
  private String docYear;

  public static final String JSON_PROPERTY_DOC_VALIDITY = "docValidity";
  @Nullable
  private LocalDate[] docValidity;

  public DocumentsServiceResponse() {
  }

  public DocumentsServiceResponse docName(@Nullable String docName) {
    
    this.docName = docName;
    return this;
  }

  /**
   * Get docName
   * @return docName
   */
  @Nullable
  @JsonProperty(JSON_PROPERTY_DOC_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocName() {
    return docName;
  }


  @JsonProperty(JSON_PROPERTY_DOC_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocName(@Nullable String docName) {
    this.docName = docName;
  }

  public DocumentsServiceResponse docLocation(@Nullable String docLocation) {
    
    this.docLocation = docLocation;
    return this;
  }

  /**
   * Get docLocation
   * @return docLocation
   */
  @Nullable
  @JsonProperty(JSON_PROPERTY_DOC_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocLocation() {
    return docLocation;
  }


  @JsonProperty(JSON_PROPERTY_DOC_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocLocation(@Nullable String docLocation) {
    this.docLocation = docLocation;
  }

  public DocumentsServiceResponse docType(@Nullable String docType) {
    
    this.docType = docType;
    return this;
  }

  /**
   * Get docType
   * @return docType
   */
  @Nullable
  @JsonProperty(JSON_PROPERTY_DOC_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocType() {
    return docType;
  }


  @JsonProperty(JSON_PROPERTY_DOC_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocType(@Nullable String docType) {
    this.docType = docType;
  }

  public DocumentsServiceResponse docYear(@Nullable String docYear) {
    
    this.docYear = docYear;
    return this;
  }

  /**
   * Get docYear
   * @return docYear
   */
  @Nullable
  @JsonProperty(JSON_PROPERTY_DOC_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocYear() {
    return docYear;
  }


  @JsonProperty(JSON_PROPERTY_DOC_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocYear(@Nullable String docYear) {
    this.docYear = docYear;
  }


  /**
   * Get docValidity
   * @return docValidity
   */
  @Nullable
  @JsonProperty(JSON_PROPERTY_DOC_VALIDITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate[] getDocValidity() {
    return docValidity;
  }


  @JsonProperty(JSON_PROPERTY_DOC_VALIDITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocYear(@Nullable LocalDate[] docValidity) {
    this.docValidity = docValidity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentsServiceResponse document = (DocumentsServiceResponse) o;
    return Objects.equals(this.docName, document.docName) &&
        Objects.equals(this.docLocation, document.docLocation) &&
        Objects.equals(this.docType, document.docType) &&
        Objects.equals(this.docYear, document.docYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docName, docLocation, docType, docYear);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    sb.append("    docName: ").append(toIndentedString(docName)).append("\n");
    sb.append("    docLocation: ").append(toIndentedString(docLocation)).append("\n");
    sb.append("    docType: ").append(toIndentedString(docType)).append("\n");
    sb.append("    docYear: ").append(toIndentedString(docYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

