/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.angadi.springoauthclient.models.responses;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import jakarta.annotation.Generated;
import jakarta.annotation.Nullable;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;


/**
 * RoomReservation
 */
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-24T19:11:07.521215600-04:00[America/New_York]", comments = "Generator version: 7.15.0")
public class RoomReservation {
  public static final String SERIALIZED_NAME_ROOM_I_D = "room_ID";
  @SerializedName(SERIALIZED_NAME_ROOM_I_D)
  @Nullable
  @JsonProperty("room_ID")
  private Long room_ID;

  public static final String SERIALIZED_NAME_GUEST_I_D = "guest_ID";
  @JsonProperty("guest_ID")
  @SerializedName(SERIALIZED_NAME_GUEST_I_D)
  @Nullable
  private Long guestID;

  public static final String SERIALIZED_NAME_ROOM_NAME = "room_name";
  @SerializedName(SERIALIZED_NAME_ROOM_NAME)
  @JsonProperty("room_name")
  @Nullable
  private String roomName;

  public static final String SERIALIZED_NAME_ROOM_NUMBER = "room_number";
  @JsonProperty("room_number")
  @SerializedName(SERIALIZED_NAME_ROOM_NUMBER)
  @Nullable
  private String roomNumber;

  public static final String SERIALIZED_NAME_FIRST_NAME = "first_name";
  @JsonProperty("first_name")
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  @Nullable
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "last_name";
  @JsonProperty("last_name")
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  @Nullable
  private String lastName;

  public static final String SERIALIZED_NAME_DATE = "date";
  @JsonProperty("date")

  @SerializedName(SERIALIZED_NAME_DATE)
  @Nullable
  private OffsetDateTime date;

  public RoomReservation() {
  }

  public RoomReservation roomID(@Nullable Long roomID) {
    this.room_ID = roomID;
    return this;
  }

  /**
   * Get roomID
   * @return roomID
   */
  @Nullable
  public Long getRoom_ID() {
    return room_ID;
  }

  public void setRoom_ID(@Nullable Long room_ID) {
    this.room_ID = room_ID;
  }


  public RoomReservation guestID(@Nullable Long guestID) {
    this.guestID = guestID;
    return this;
  }

  /**
   * Get guestID
   * @return guestID
   */
  @Nullable
  public Long getGuestID() {
    return guestID;
  }

  public void setGuestID(@Nullable Long guestID) {
    this.guestID = guestID;
  }


  public RoomReservation roomName(@Nullable String roomName) {
    this.roomName = roomName;
    return this;
  }

  /**
   * Get roomName
   * @return roomName
   */
  @Nullable
  public String getRoomName() {
    return roomName;
  }

  public void setRoomName(@Nullable String roomName) {
    this.roomName = roomName;
  }


  public RoomReservation roomNumber(@Nullable String roomNumber) {
    this.roomNumber = roomNumber;
    return this;
  }

  /**
   * Get roomNumber
   * @return roomNumber
   */
  @Nullable
  public String getRoomNumber() {
    return roomNumber;
  }

  public void setRoomNumber(@Nullable String roomNumber) {
    this.roomNumber = roomNumber;
  }


  public RoomReservation firstName(@Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @Nullable
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(@Nullable String firstName) {
    this.firstName = firstName;
  }


  public RoomReservation lastName(@Nullable String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @Nullable
  public String getLastName() {
    return lastName;
  }

  public void setLastName(@Nullable String lastName) {
    this.lastName = lastName;
  }


  public RoomReservation date(@Nullable OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @Nullable
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(@Nullable OffsetDateTime date) {
    this.date = date;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomReservation roomReservation = (RoomReservation) o;
    return Objects.equals(this.room_ID, roomReservation.room_ID) &&
        Objects.equals(this.guestID, roomReservation.guestID) &&
        Objects.equals(this.roomName, roomReservation.roomName) &&
        Objects.equals(this.roomNumber, roomReservation.roomNumber) &&
        Objects.equals(this.firstName, roomReservation.firstName) &&
        Objects.equals(this.lastName, roomReservation.lastName) &&
        Objects.equals(this.date, roomReservation.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(room_ID, guestID, roomName, roomNumber, firstName, lastName, date);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomReservation {\n");
    sb.append("    roomID: ").append(toIndentedString(room_ID)).append("\n");
    sb.append("    guestID: ").append(toIndentedString(guestID)).append("\n");
    sb.append("    roomName: ").append(toIndentedString(roomName)).append("\n");
    sb.append("    roomNumber: ").append(toIndentedString(roomNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("room_ID", "guest_ID", "room_name", "room_number", "first_name", "last_name", "date"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RoomReservation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RoomReservation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RoomReservation is not found in the empty JSON string", RoomReservation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RoomReservation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RoomReservation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("room_name") != null && !jsonObj.get("room_name").isJsonNull()) && !jsonObj.get("room_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `room_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("room_name").toString()));
      }
      if ((jsonObj.get("room_number") != null && !jsonObj.get("room_number").isJsonNull()) && !jsonObj.get("room_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `room_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("room_number").toString()));
      }
      if ((jsonObj.get("first_name") != null && !jsonObj.get("first_name").isJsonNull()) && !jsonObj.get("first_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `first_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("first_name").toString()));
      }
      if ((jsonObj.get("last_name") != null && !jsonObj.get("last_name").isJsonNull()) && !jsonObj.get("last_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RoomReservation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RoomReservation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RoomReservation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RoomReservation.class));

       return (TypeAdapter<T>) new TypeAdapter<RoomReservation>() {
           @Override
           public void write(JsonWriter out, RoomReservation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RoomReservation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RoomReservation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RoomReservation
   * @throws IOException if the JSON string is invalid with respect to RoomReservation
   */
  public static RoomReservation fromJson(String jsonString) throws IOException {
    return new Gson().fromJson(jsonString, RoomReservation.class);
  }

  /**
   * Convert an instance of RoomReservation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return new Gson().toJson(this);
  }
}

